get:
  operationId: getCampaignReportsConfig
  tags:
    - Certification Campaigns
  summary: Get Campaign Reports Configuration
  description: >- 
    Fetches configuration for campaign reports. Currently it includes only one element - identity attributes defined as custom report columns.

    Requires roles of CERT_ADMIN and ORG_ADMIN.

  security:
    - UserContextAuth: [ idn:campaign-reports-config:read ]
  responses:
    '200':
      description: Campaign Report Configuration
      content:
        application/json:
          schema:
            $ref: '../schemas/CampaignReportsConfig.yaml'
    '400':
      $ref: '../responses/400.yaml'
    '401':
      $ref: '../responses/401.yaml'
    '403':
      $ref: '../responses/403.yaml'
    '429':
      $ref: '../responses/429.yaml'
    '500':
      $ref: '../responses/500.yaml'